function add(x, y) {
  return (x + y);
}

function sub (x, y) {
  return (x - y);
}

function mul(x, y) {
  return (x * y);
}

function modulo(x, y) {
  return (x % y);
}

function neg(x) {
  return -x;
}

function id(x) {
  return x;
}

function arg1(a, b, c, d, e, f, g, h, i ,j) {
  return a;
}

function arg2(a, b, c, d, e, f, g, h, i ,j) {
  return b;
}

function arg3(a, b, c, d, e, f, g, h, i ,j) {
  return c;
}
function arg4(a, b, c, d, e, f, g, h, i ,j) {
  return d;
}
function arg5(a, b, c, d, e, f, g, h, i ,j) {
  return e;
}
function arg6(a, b, c, d, e, f, g, h, i ,j) {
  return f;
}
function arg7(a, b, c, d, e, f, g, h, i ,j) {
  return g;
}
function arg8(a, b, c, d, e, f, g, h, i ,j) {
  return h;
}
function arg9(a, b, c, d, e, f, g, h, i ,j) {
  return i;
}
function arg10(a, b, c, d, e, f, g, h, i ,j) {
  return j;
}

add(1, 1);
