build:
  image: maven:latest
  stage: build
  tags:
    - docker
  script:
    - mvn package

test:
  image: ubuntu:latest 
  stage: test
  tags:
    - docker
  before_script:
    - apt install build-essential
  script:
    - make runTest
