build:
  image: maven:latest
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - target/
  script:
    - mvn package

test:
  image: ubuntu:latest 
  stage: test
  tags:
    - docker
  before_script:
    - apt update
    - apt install -y build-essential
  script:
    - make runTest
