build:
  image: maven:latest
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - target/
  script:
    - mvn package

test_parsing:
  image: ubuntu:rolling
  stage: test
  tags:
    - docker
  before_script:
    - apt upate
    - apt install -y build-essential openjdk-13-jre-headless
  script:
     - make testJava

test_compilation:
  image: ubuntu:rolling
  stage: test
  tags:
    - docker
  before_script:
    - apt update
    - apt install -y build-essential openjdk-13-jre-headless
  script:
    - make test
