int arg1(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg2(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg3(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg4(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg5(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg6(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg7(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg8(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg9(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg10(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);

int get1();
int get2();
int get3();
int get4();
int get5();
int get6();
int get7();
int get8();
int get9();
int get10();