long arg1(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);
long arg2(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);
long arg3(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);
long arg4(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);
long arg5(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);
long arg6(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);
long arg7(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);
long arg8(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);
long arg9(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);
long arg10(long a, long b, long c, long d, long e, long f, long g, long h, long i, long j);

long get1();
long get2();
long get3();
long get4();
long get5();
long get6();
long get7();
long get8();
long get9();
long get10();

double farg1(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg2(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg3(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg4(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg5(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg6(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg7(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg8(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg9(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg10(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);

double fargMix1(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);
long fargMix2(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);
double fargMix3(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);
long fargMix4(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);
double fargMix5(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);
long fargMix6(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);
double fargMix7(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);
long fargMix8(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);
double fargMix9(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);
long fargMix10(double a, long b, double c, long d, double e, long f, double g, long h, double i, long j);

double fget1();
double fget2();
double fget3();
double fget4();
double fget5();
double fget6();
double fget7();
double fget8();
double fget9();
double fget10();

double fgetMix1();
long fgetMix2();
double fgetMix3();
long fgetMix4();
double fgetMix5();
long fgetMix6();
double fgetMix7();
long fgetMix8();
double fgetMix9();
long fgetMix10();