int arg1(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg2(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg3(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg4(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg5(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg6(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg7(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg8(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg9(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);
int arg10(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j);

int get1();
int get2();
int get3();
int get4();
int get5();
int get6();
int get7();
int get8();
int get9();
int get10();

double farg1(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg2(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg3(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg4(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg5(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg6(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg7(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg8(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg9(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);
double farg10(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j);

double fargMix1(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);
int fargMix2(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);
double fargMix3(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);
int fargMix4(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);
double fargMix5(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);
int fargMix6(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);
double fargMix7(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);
int fargMix8(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);
double fargMix9(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);
int fargMix10(double a, int b, double c, int d, double e, int f, double g, int h, double i, int j);

double fget1();
double fget2();
double fget3();
double fget4();
double fget5();
double fget6();
double fget7();
double fget8();
double fget9();
double fget10();

double fgetMix1();
int fgetMix2();
double fgetMix3();
int fgetMix4();
double fgetMix5();
int fgetMix6();
double fgetMix7();
int fgetMix8();
double fgetMix9();
int fgetMix10();